# Generated by Django 3.2.19 on 2023-05-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='Администратор приложения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Должность'),
        ),
    ]
